version: "3"
services:
  db:
    image: "postgres"
    container_name: "heq_server_pg"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=simple
      - POSTGRES_DB=dev_heq_server_pg
    ports:
      - "54320:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  test-db:
    image: "postgres"
    container_name: "heq_server_pg__test"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=simple
      - POSTGRES_DB=test_heq_server_pg
    ports:
      - "54321:5432"
    volumes:
      - ./test-postgres-data:/var/lib/postgresql/data
